# OrbisClimate Optimized Configuration
# Performance-focused settings with improved weather transitions

# ======= PERFORMANCE SETTINGS (PRIORITY) =======
performance:
  # Particle optimization
  particles:
    # Reduce particles when many players are nearby
    optimize_for_player_count: true

    # Maximum particles per player regardless of effects
    max_particles_per_player: 100

    # Update frequency for climate effects (in ticks)
    climate_update_interval: 40      # Every 2 seconds instead of 1
    temperature_update_interval: 2400 # Every 2 minutes instead of 1

    # Use batch processing for particles (reduces lag)
    use_batch_processing: true

    # Distance-based Level of Detail (LOD)
    use_distance_lod: true

    # View frustum culling - don't render particles behind players
    use_view_culling: true
    fov_threshold: -0.5  # 120 degree field of view

    # Adaptive quality based on TPS
    adaptive_quality: true
    min_tps_threshold: 15.0  # Below this TPS, reduce effects
    quality_reduction_factor: 0.5  # Multiply particle count by this when low TPS

  # Caching
  cache:
    # How long to cache player zone detection (in seconds)
    player_zone_cache_duration: 60

    # Clear cache when player moves this many blocks
    cache_clear_distance: 100

    # Cache exposure calculations for indoor detection
    cache_exposure_calculations: true
    exposure_cache_duration: 30

    # Cache biome lookups
    cache_biome_lookups: true
    biome_cache_duration: 120

  # Advanced optimizations
  advanced:
    # Use async tasks for particle processing
    async_particles: true

    # Reduce calculations for distant players
    distance_optimization: true

    # Maximum distance for full effects
    max_effect_distance: 80

    # Skip effects for players with low frame rates
    skip_effects_low_fps: true
    min_fps_threshold: 30

    # Intelligent effect scaling
    smart_scaling: true
    player_density_threshold: 10  # Start reducing effects when 10+ players nearby

  # TPS thresholds for performance scaling
  tps_thresholds:
    low_performance: 15.0    # Below this TPS = performance mode
    medium_performance: 18.0 # Below this TPS = reduced effects
    high_performance: 19.5   # Above this TPS = full effects

  # NEW: Weather progression performance settings
  weather_progression:
    # Limit progression effects based on player count
    max_players_for_full_effects: 20

    # Reduce progression particle density in performance mode
    performance_mode_multiplier: 0.5

    # Skip progression effects if TPS is too low
    min_tps_for_effects: 16.0

    # Batch process progression effects to reduce lag
    use_batch_processing: true
    batch_size: 5                # Process 5 players per tick

    # Cache progression calculations
    cache_progression_checks: true
    cache_duration_seconds: 30

# ======= PERFORMANCE MONITORING (SIMPLIFIED) =======
monitoring:
  # Enable performance monitoring
  enabled: true

  # Log warnings when TPS drops below threshold
  tps_warning_threshold: 18.0

  # Automatically reduce effects when performance is poor
  auto_reduce_effects: true

  # Monitor memory usage
  memory_monitoring: true
  memory_warning_threshold: 85  # Percentage

# ======= WEATHER SYSTEM OPTIMIZATION + TRANSITIONS (IMPROVED) =======
weather:
  # MAJOR OPTIMIZATION: Check weather every 2 minutes instead of 1 minute
  update_interval_ticks: 2400  # 2400 ticks = 2 minutes (was 1200 = 1 minute)

  # Process multiple worlds in batches to prevent lag spikes
  batch_updates: true
  batch_size: 5               # How many worlds to process per batch

  # CRITICAL OPTIMIZATION: Skip applying weather if it hasn't changed
  skip_unchanged: true         # This prevents 90% of redundant Bukkit API calls

  # Weather event frequency optimization
  event_check_frequency: 4     # Check for blizzards/sandstorms every 4th weather cycle

  # ======= NEW: WEATHER PERSISTENCE AND TRANSITIONS =======
  transitions:
    # Enable improved weather transition system
    enabled: true

    # Minimum duration a weather type must last before it can change (in seconds)
    min_weather_duration: 300    # 5 minutes minimum

    # Weather persistence settings (how long each weather type tends to last)
    persistence:
      clear:
        min_duration: 300        # 5 minutes
        max_duration: 900        # 15 minutes
      light_rain:
        min_duration: 240        # 4 minutes
        max_duration: 600        # 10 minutes
      heavy_rain:
        min_duration: 180        # 3 minutes
        max_duration: 600        # 10 minutes
      thunderstorm:
        min_duration: 300        # 5 minutes
        max_duration: 900        # 15 minutes
      snow:
        min_duration: 600        # 10 minutes
        max_duration: 1500       # 25 minutes
      blizzard:
        min_duration: 480        # 8 minutes
        max_duration: 1200       # 20 minutes
      sandstorm:
        min_duration: 360        # 6 minutes
        max_duration: 900        # 15 minutes

    # Transition duration settings (how long it takes to change between weather types)
    transition_durations:
      quick_change: 30           # 30 seconds (clear <-> light rain)
      medium_change: 90          # 1.5 minutes (rain <-> heavy rain)
      slow_change: 180           # 3 minutes (heavy rain <-> thunderstorm)

    # Weather continuity - chance for weather to continue to next time period
    continuity:
      morning_to_afternoon: 0.6  # 60% chance
      afternoon_to_evening: 0.5  # 50% chance
      evening_to_night: 0.4      # 40% chance
      night_to_morning: 0.3      # 30% chance

    # Notify players about weather transitions
    notify_transitions: true
    notify_weather_changes: true

# ======= WEATHER PROGRESSION (REDESIGNED TO WORK WITH FORECAST) =======
weather_progression:
  # Enable enhanced weather progression effects (works WITH forecast, not against it)
  enabled: true

  # Enhanced transitions between forecast weather changes
  enhanced_transitions:
    enabled: true

    # Show warning effects before weather transitions
    show_warnings: true
    warning_time_hours: 2

    # Transition durations (how long visual effects last during weather changes)
    transition_durations:
      quick_change: 30           # Clear <-> Light Rain (30 seconds)
      medium_change: 90          # Light Rain <-> Heavy Rain (1.5 minutes)
      slow_change: 180           # Heavy Rain <-> Thunderstorm (3 minutes)
      storm_change: 240          # Any storm weather (4 minutes)

  # Pre-storm warning effects (when storms are forecast to arrive soon)
  pre_storm_effects:
    enabled: true
    duration_minutes: 5          # How long before storm to show warnings

    # Lightning warnings before thunderstorms
    lightning_warnings:
      enabled: true
      interval_seconds: 45       # Time between warning flashes
      max_warnings: 6            # Maximum number of warnings to show
      distance_range: 100        # How far away the warning lightning appears

    # Building cloud effects before storms
    cloud_buildup:
      enabled: true
      particle_density: 0.8      # How dense the cloud particles are
      height_range: 25           # How high above players to show clouds

  # Active weather enhancements (during forecast weather)
  active_weather_effects:
    # Enhanced lightning during thunderstorms
    enhanced_lightning:
      enabled: true
      frequency_multiplier: 1.5  # How much more frequent than normal
      intensity_multiplier: 1.2  # How intense the effects are

    # Hail effects during heavy rain/storms
    hail:
      enabled: true
      chance_during_rain: 0.3    # 30% chance during heavy rain
      chance_during_storm: 0.6   # 60% chance during thunderstorms
      duration_minutes: 3        # How long hail lasts
      particle_density: 1.0      # Density of hail particles
      sound_effects: true        # Play hail impact sounds

      # Which climate zones can have hail
      allowed_zones:
        - TEMPERATE
        - ARCTIC                 # Arctic zones can have ice storms

      # Which biomes are excluded from hail
      excluded_biomes:
        - DESERT
        - BADLANDS
        - ERODED_BADLANDS
        - WOODED_BADLANDS

  # Post-storm effects (after storms end according to forecast)
  post_storm_effects:
    enabled: true
    duration_minutes: 3          # How long clearing effects last

    # Clearing sky effects
    sky_clearing:
      enabled: true
      particle_density: 0.6      # Density of clearing particles
      rainbow_chance: 0.2        # 20% chance of rainbow effects after rain

  # Weather intensity variations (add variety to forecast weather)
  intensity_variations:
    enabled: true

    # Vary intensity during long weather periods
    dynamic_intensity:
      enabled: true
      variation_frequency: 300   # Change intensity every 5 minutes
      max_intensity_change: 0.3  # Maximum change in intensity (±30%)

    # Gusting effects during wind-related weather
    gusting_effects:
      enabled: true
      gust_frequency: 120        # Gusts every 2 minutes on average
      gust_duration: 15          # Each gust lasts 15 seconds
      gust_intensity: 1.5        # Gusts are 50% more intense

  # Forecast integration settings
  forecast_integration:
    # How far ahead to look for weather transitions (in hours)
    forecast_lookahead: 3

    # React to forecast transitions marked in the detailed forecast
    use_forecast_transitions: true

    # Override progression if forecast says otherwise
    respect_forecast_priority: true

    # Log when progression effects are triggered by forecast changes
    log_forecast_triggers: true

# ======= WIND SYSTEM (OPTIMIZED) =======
wind:
  enabled: true
  interior_height_distance: 50  # Reduced from 50 for better performance
  min_height: 55
  max_particles: 100
  particle_range: 8.0  # Reduced from 10.0

  # Optimized wind chances
  chances:
    clear_weather: 8.0      # Slightly reduced
    rain: 20.0              # Reduced from 25.0
    snow: 12.0              # Reduced from 15.0
    thunderstorm: 75.0     # Keep high for storms

  duration:
    min_seconds: 25         # Slightly reduced
    max_seconds: 90         # Reduced from 120

# ======= BLIZZARD SYSTEM (OPTIMIZED + CONTROLS) =======
blizzard:
  enabled: false              # NEW: Enable/disable blizzards
  damage: 1.0
  min_freezing_height: 65
  particle_range: 15        # Reduced from 20
  particle_y_range: 25      # Reduced from 30
  particle_multiplier: 1.5  # Reduced from 1.0
  temperature_threshold: 0.15

  # Localized blizzard system
  localized_blizzards: true
  max_players_per_blizzard: 10

# ======= SANDSTORM SYSTEM (OPTIMIZED + CONTROLS) =======
sandstorm:
  enabled: false # NEW: Enable/disable sandstorms
  min_height: 62
  particle_range: 12        # Reduced from 15
  particle_y_range: 20      # Reduced from 25
  particle_multiplier: 1.2  # Reduced from 1.5
  blindness_duration: 100
  slowness_duration: 100
  slowness_amplifier: 1

  # Localized sandstorm system
  localized_sandstorms: true
  max_players_per_sandstorm: 8

# ======= CLIMATE ZONE SYSTEM (OPTIMIZED + ARID ZONES) =======
climate_zones:
  # Simplified world configuration for better performance
  world:
    arctic:
      enabled: true
      use_coordinates: false  # Biome-based is more efficient
      temperature_modifier: 0.7
      biomes:
        - SNOWY_PLAINS
        - SNOWY_TAIGA
        - SNOWY_SLOPES
        - SNOWY_BEACH
        - FROZEN_RIVER
        - FROZEN_OCEAN
        - DEEP_FROZEN_OCEAN
        - ICE_SPIKES
        - GROVE
        - JAGGED_PEAKS
        - FROZEN_PEAKS
        - TAIGA

    temperate:
      enabled: true
      use_coordinates: false
      temperature_modifier: 1.0
      biomes:
        - PLAINS
        - FOREST
        - BIRCH_FOREST
        - DARK_FOREST
        - FLOWER_FOREST
        - RIVER
        - BEACH
        - OCEAN
        - DEEP_OCEAN
        - LUKEWARM_OCEAN
        - WARM_OCEAN
        - WINDSWEPT_HILLS
        - WINDSWEPT_FOREST

    desert:
      enabled: true
      use_coordinates: false
      temperature_modifier: 1.4
      disable_rain: false  # Desert can still get rare rain
      biomes:
        - DESERT

    arid:                   # NEW: Arid zone
      enabled: true
      use_coordinates: false
      temperature_modifier: 1.3
      disable_rain: true    # NEW: No rain in arid zones
      biomes:
        - BADLANDS
        - ERODED_BADLANDS
        - WOODED_BADLANDS

# ======= DROUGHT SYSTEM (SIMPLIFIED) =======
drought:
  min_clear_days: 7  # Increased to make droughts less frequent
  max_duration_days: 10  # Reduced from 15

  effects:
    temperature_bonus: 12  # Reduced from 15

    heat_exhaustion:
      enabled: true
      chance_per_minute: 15  # Reduced from 25
      effects:
        - SLOWNESS:0:60   # Reduced duration

    crop_effects:
      enabled: false  # Disabled for performance

# ======= TEMPERATURE SYSTEM (OPTIMIZED) =======
temperature:
  enabled: true

  base_temperatures:
    arctic: -15
    temperate: 15
    desert: 35
    arid: 30              # NEW: Arid zone temperature

  player_effects:
    cold:
      mild_cold: 0
      cold: -10
      severe_cold: -25

      effects:
        mild_cold: []
        cold:
          - SLOWNESS:0:80  # Reduced duration
        severe_cold:
          - SLOWNESS:1:80

    heat:
      mild_heat: 30
      hot: 40
      severe_heat: 50

      effects:
        mild_heat: []
        hot:
          - HUNGER:0:80
        severe_heat:
          - HUNGER:1:80
          - SLOWNESS:0:80

# ======= AURORA SYSTEM (OPTIMIZED) =======
aurora:
  enabled: false
  night_only: false
  chance_per_minute: 10  # Reduced from 15

  colors:
    - "0,255,100"
    - "0,100,255"
    - "255,0,255"

  particles:
    count: 20          # Reduced from 30
    radius: 12         # Reduced from 15
    height_offset: 25  # Reduced from 30

# ======= HEAT MIRAGE SYSTEM (OPTIMIZED) =======
heat_mirages:
  enabled: false
  day_only: false
  chance_per_minute: 15  # Reduced from 20
  drought_chance_multiplier: 1.5  # Reduced from 2.0

  particles:
    count: 15         # Reduced from 20
    range: 25         # Reduced from 30
    shimmer_speed: 300  # Slower for less CPU usage

# ======= DYNAMIC SOUND SYSTEM (OPTIMIZED) =======
dynamic_sounds:
  enabled: true
  indoor_volume_multiplier: 0.3
  update_interval_ticks: 100  # Reduced frequency from 60

  seasonal_sounds:
    enabled: true
    volume_multiplier: 0.6  # Reduced from 0.8

  time_sounds:
    enabled: true
    night_sounds: true
    dawn_sounds: true
    dusk_sounds: true

# ======= INTEGRATION SETTINGS =======
integration:
  realistic_seasons:
    use_time_system: true
    use_temperature_system: true
    enhanced_seasonal_effects: false  # Disabled for performance

# ======= PLAYER PREFERENCES =======
player_settings:
  allow_particle_toggle: true
  default_particles_enabled: true
  save_preferences: true

# ======= ENHANCED FEATURES (SELECTIVE) =======
enhanced_features:
  wind_trails:
    enabled: true
    stream_count_multiplier: 0.8  # Reduced
    trail_length: 4               # Reduced from 6

  blizzard_walls:
    enabled: false
    wall_density: 0.4    # Reduced from 0.6
    wall_height: 4       # Reduced from 6
    wall_width: 12       # Reduced from 15

  seasonal_wildlife:
    enabled: false  # Disabled for performance

  weather_transitions:
    enabled: true
    pre_storm_effects: true
    post_storm_effects: true
    enhanced_lightning: true

# ======= WEATHER CONTROL =======
weather_control:
  # Basic snow/ice prevention during OrbisClimate weather
  prevent_snow_placement: true
  prevent_ice_formation: true

  # ADVANCED: Prevent ALL snow/ice regardless of weather (overrides RealisticSeasons)
  prevent_all_snow: true       # Set to true to prevent ALL snow formation
  prevent_all_ice: true       # Set to true to prevent ALL ice formation

  # NUCLEAR OPTION: Override all other weather plugins
  override_all_weather: false  # Set to true to override RealisticSeasons weather changes

  # Standard options
  disable_vanilla_weather: true
  restore_vanilla_on_shutdown: true

# ======= NOTIFICATIONS =======
notifications:
  permission: "orbisclimate.notifications"
  zone_change_notifications: false    # Disabled to reduce spam
  drought_notifications: true
  temperature_warnings: true
  wind_event_notifications: false     # Disabled to reduce spam
  weather_progression_notifications: true
  blizzard_messages: true             # NEW: Blizzard notifications
  sandstorm_messages: true            # NEW: Sandstorm notifications
  weather_transition_notifications: true  # NEW: Notify about weather transitions

  # NEW: Weather progression notifications
  weather_progression:
    enabled: true

    # Notify about upcoming weather changes
    forecast_warnings: true
    warning_time_hours: 1        # Warn 1 hour before weather changes

    # Notify about weather transitions in progress
    transition_notifications: true

    # Notify about special effects (hail, enhanced lightning, etc.)
    special_effect_notifications: true

    # Notify about weather intensity changes
    intensity_change_notifications: false  # Usually too spammy

    # Permission required to see progression notifications
    progression_permission: "orbisclimate.notifications"

# ======= DEBUG AND LOGGING (ENHANCED) =======
debug:
  enabled: true                      # Enable to see forecast logs
  log_zone_changes: false
  log_temperature_changes: false
  log_drought_events: true
  log_performance: false
  log_particle_optimizations: false

  # Weather system debug options - ENABLE THESE TO SEE FORECAST IN ACTION
  log_weather_transitions: true      # ENABLE: See when weather changes per forecast
  log_weather_applications: true     # ENABLE: See when weather is applied to worlds
  log_snow_prevention: false         # Log when snow placement is prevented
  log_weather_interference: false    # Log when vanilla weather is blocked

  # NEW: Weather optimization debug options
  log_weather_optimizations: false   # Log when weather is actually applied vs skipped
  log_weather_skips: false          # Log when weather application is skipped (unchanged)
  log_weather_persistence: true     # ENABLE: Log weather persistence and duration info

  # NEW: Weather progression debug options
  weather_progression:
    # Log when progression stages change
    log_progression_changes: true

    # Log when forecast triggers progression effects
    log_forecast_triggers: true

    # Log transition timing and duration
    log_transition_timing: true

    # Log when special effects start/stop
    log_special_effects: true

    # Show detailed progression info in debug commands
    include_in_debug_commands: true

# ======= COMPATIBILITY =======
compatibility:
  # Disable features that conflict with other plugins
  disable_weather_override: false

  # Work with other particle plugins
  respect_particle_limits: true

  # Reduce effects near other plugin areas
  smart_area_detection: true

# ======= EXPERIMENTAL FEATURES (DISABLED) =======
experimental:
  particle_physics:
    enabled: false
  air_pressure:
    enabled: false
  dynamic_biome_temp:
    enabled: false
  ml_weather:
    enabled: false