# OrbisClimate Configuration
# A realistic wind system that responds to weather conditions and seasons

wind:
  # Enable or disable the wind system entirely
  enabled: true

  # How many blocks to check above a player to determine if they're indoors
  # Higher values = better detection of high ceilings but more performance cost
  # Default: 50 blocks (suitable for large buildings)
  interior_height_distance: 50

  # Maximum number of particles to show per player during wind events
  # Higher values = more visual effect but may cause lag
  max_particles: 100

  # How far around the player to spawn wind particles (in blocks)
  particle_range: 10.0

  # Wind event chances (percentage chance every 30 seconds)
  # These base chances are modified by seasonal multipliers:
  # Winter: +40%, Spring: +20%, Autumn: +30%, Summer: -20%
  chances:
    clear_weather: 10.0      # 10% chance during clear weather
    rain: 25.0               # 25% chance during rain
    snow: 15.0               # 15% chance during snow
    thunderstorm: 100.0      # 100% chance during thunderstorms

  # How long wind events last (in seconds)
  # Duration is also modified by seasons:
  # Winter: +30%, Spring: +10%, Autumn: +20%, Summer: no change
  duration:
    min_seconds: 30          # Minimum duration
    max_seconds: 120         # Maximum duration

blizzard:
  damage: 1.0                    # Damage per effect tick
  min_freezing_height: 60        # Minimum Y level for effects
  particle_range: 20             # Particle spawn radius
  particle_y_range: 30           # Vertical particle range
  particle_multiplier: 1.0       # Particle density multiplier
  temperature_threshold: 0.15    # Biome temperature threshold

  wind:
    min_height: 62              # Wind threshold (valleys protected)

  blizzard:
    min_freezing_height: 62     # Blizzard threshold (higher = more exclusive)

sandstorm:
  min_height: 62              # Minimum Y level for effects
  particle_range: 15          # Particle spawn radius
  particle_y_range: 25        # Vertical particle range
  particle_multiplier: 1.5    # Particle density (1.5x normal)
  blindness_duration: 100     # Blindness duration (5 seconds)
  slowness_duration: 100      # Slowness duration (5 seconds)
  slowness_amplifier: 1       # Slowness level (0=I, 1=II, 2=III)

# Integration Information:
# - RealisticSeasons: If installed, the plugin will use RealisticSeasons time and seasons
#   to generate more realistic weather patterns and seasonal wind effects
# - Seasonal Effects:
#   * Winter: More frequent and intense wind, longer duration, snow particles
#   * Spring: Variable wind patterns, fresh green particles in forests
#   * Summer: Less frequent wind, more stable patterns
#   * Autumn: Frequent wind, orange/brown leaf particles in forests
# - Weather-Responsive Wind:
#   * Clear weather: Light, infrequent wind
#   * Rain: Moderate wind with rain-themed particles
#   * Snow: Gentle wind with snowflake particles
#   * Thunderstorms: Strong, frequent wind
#   * Blizzards: Very strong wind with intense snow particles
# - Biome-Specific Particles:
#   * Deserts: Sand-colored particles
#   * Forests: Leaf particles (color varies by season)
#   * Oceans/Beaches: White foam particles
#   * Swamps: Murky green particles
#   * Snow Biomes: Always snow particles