# OrbisClimate Optimized Configuration
# Performance-focused settings for better server performance

# ======= PERFORMANCE SETTINGS (PRIORITY) =======
performance:
  # Particle optimization
  particles:
    # Reduce particles when many players are nearby
    optimize_for_player_count: true

    # Maximum particles per player regardless of effects
    max_particles_per_player: 100

    # Update frequency for climate effects (in ticks)
    climate_update_interval: 40      # Every 2 seconds instead of 1
    temperature_update_interval: 2400 # Every 2 minutes instead of 1

    # Use batch processing for particles (reduces lag)
    use_batch_processing: true

    # Distance-based Level of Detail (LOD)
    use_distance_lod: true

    # View frustum culling - don't render particles behind players
    use_view_culling: true
    fov_threshold: -0.5  # 120 degree field of view

    # Adaptive quality based on TPS
    adaptive_quality: true
    min_tps_threshold: 15.0  # Below this TPS, reduce effects
    quality_reduction_factor: 0.5  # Multiply particle count by this when low TPS

  # Caching
  cache:
    # How long to cache player zone detection (in seconds)
    player_zone_cache_duration: 60

    # Clear cache when player moves this many blocks
    cache_clear_distance: 100

    # Cache exposure calculations for indoor detection
    cache_exposure_calculations: true
    exposure_cache_duration: 30

    # Cache biome lookups
    cache_biome_lookups: true
    biome_cache_duration: 120

  # Advanced optimizations
  advanced:
    # Use async tasks for particle processing
    async_particles: true

    # Reduce calculations for distant players
    distance_optimization: true

    # Maximum distance for full effects
    max_effect_distance: 80

    # Skip effects for players with low frame rates
    skip_effects_low_fps: true
    min_fps_threshold: 30

    # Intelligent effect scaling
    smart_scaling: true
    player_density_threshold: 10  # Start reducing effects when 10+ players nearby

# ======= PERFORMANCE MONITORING =======
monitoring:
  # Enable performance monitoring
  enabled: true

  # Log warnings when TPS drops below threshold
  tps_warning_threshold: 18.0

  # Automatically reduce effects when performance is poor
  auto_reduce_effects: true

  # Monitor memory usage
  memory_monitoring: true
  memory_warning_threshold: 85  # Percentage

  # Track particle counts per player
  track_particle_counts: true
  max_particles_per_player_warning: 150

# ======= WIND SYSTEM (OPTIMIZED) =======
wind:
  enabled: true
  interior_height_distance: 30  # Reduced from 50 for better performance
  min_height: 50
  max_particles: 50  # Reduced from 100
  particle_range: 8.0  # Reduced from 10.0

  # Optimized wind chances
  chances:
    clear_weather: 8.0      # Slightly reduced
    rain: 20.0              # Reduced from 25.0
    snow: 12.0              # Reduced from 15.0
    thunderstorm: 100.0     # Keep high for storms

  duration:
    min_seconds: 25         # Slightly reduced
    max_seconds: 90         # Reduced from 120

# ======= BLIZZARD SYSTEM (OPTIMIZED) =======
blizzard:
  damage: 1.0
  min_freezing_height: 60
  particle_range: 15        # Reduced from 20
  particle_y_range: 25      # Reduced from 30
  particle_multiplier: 0.8  # Reduced from 1.0
  temperature_threshold: 0.15

# ======= SANDSTORM SYSTEM (OPTIMIZED) =======
sandstorm:
  min_height: 62
  particle_range: 12        # Reduced from 15
  particle_y_range: 20      # Reduced from 25
  particle_multiplier: 1.2  # Reduced from 1.5
  blindness_duration: 100
  slowness_duration: 100
  slowness_amplifier: 1

# ======= CLIMATE ZONE SYSTEM (OPTIMIZED) =======
climate_zones:
  # Simplified world configuration for better performance
  world:
    arctic:
      enabled: true
      use_coordinates: false  # Biome-based is more efficient
      temperature_modifier: 0.7
      biomes:
        - SNOWY_PLAINS
        - SNOWY_TAIGA
        - FROZEN_OCEAN
        - ICE_SPIKES
        - TAIGA

    temperate:
      enabled: true
      use_coordinates: false
      temperature_modifier: 1.0
      biomes:
        - PLAINS
        - FOREST
        - OCEAN
        - RIVER
        - BEACH

    desert:
      enabled: true
      use_coordinates: false
      temperature_modifier: 1.4
      biomes:
        - DESERT
        - BADLANDS
        - SAVANNA

# ======= DROUGHT SYSTEM (SIMPLIFIED) =======
drought:
  min_clear_days: 7  # Increased to make droughts less frequent
  max_duration_days: 10  # Reduced from 15

  effects:
    temperature_bonus: 12  # Reduced from 15

    heat_exhaustion:
      enabled: true
      chance_per_minute: 15  # Reduced from 25
      effects:
        - SLOWNESS:0:60   # Reduced duration

    crop_effects:
      enabled: false  # Disabled for performance

# ======= TEMPERATURE SYSTEM (OPTIMIZED) =======
temperature:
  enabled: true

  base_temperatures:
    arctic: -15
    temperate: 15
    desert: 35

  player_effects:
    cold:
      mild_cold: 0
      cold: -10
      severe_cold: -25

      effects:
        mild_cold: []
        cold:
          - SLOWNESS:0:80  # Reduced duration
        severe_cold:
          - SLOWNESS:1:80
          - WITHER:0:40

    heat:
      mild_heat: 30
      hot: 40
      severe_heat: 50

      effects:
        mild_heat: []
        hot:
          - HUNGER:0:80
        severe_heat:
          - HUNGER:1:80
          - SLOWNESS:0:80

# ======= WEATHER PROGRESSION (SIMPLIFIED) =======
weather_progression:
  enabled: true
  pre_storm_duration_minutes: 3  # Reduced from 5

  lightning_warnings:
    enabled: true
    interval_seconds: 45  # Increased from 30
    warning_count: 4      # Reduced from 6

  hail:
    enabled: true
    chance_during_rain: 0.2  # Reduced from 0.3
    duration_minutes: 2      # Reduced from 3
    damage_per_second: 0.3   # Reduced from 0.5
    allowed_biomes:
      - PLAINS
      - FOREST

  transitions:
    light_to_heavy_rain: 4   # Increased from 3
    heavy_rain_to_thunderstorm: 3  # Increased from 2
    thunderstorm_to_clearing: 5     # Increased from 4
    clearing_to_clear: 3            # Increased from 2

# ======= AURORA SYSTEM (OPTIMIZED) =======
aurora:
  enabled: true
  night_only: true
  chance_per_minute: 10  # Reduced from 15

  colors:
    - "0,255,100"
    - "0,100,255"
    - "255,0,255"

  particles:
    count: 20          # Reduced from 30
    radius: 12         # Reduced from 15
    height_offset: 25  # Reduced from 30

# ======= HEAT MIRAGE SYSTEM (OPTIMIZED) =======
heat_mirages:
  enabled: true
  day_only: true
  chance_per_minute: 15  # Reduced from 20
  drought_chance_multiplier: 1.5  # Reduced from 2.0

  particles:
    count: 15         # Reduced from 20
    range: 25         # Reduced from 30
    shimmer_speed: 300  # Slower for less CPU usage

# ======= DYNAMIC SOUND SYSTEM (OPTIMIZED) =======
dynamic_sounds:
  enabled: true
  indoor_volume_multiplier: 0.3
  update_interval_ticks: 100  # Reduced frequency from 60

  seasonal_sounds:
    enabled: true
    volume_multiplier: 0.6  # Reduced from 0.8

  time_sounds:
    enabled: true
    night_sounds: true
    dawn_sounds: false    # Disabled for performance
    dusk_sounds: false    # Disabled for performance

# ======= INTEGRATION SETTINGS =======
integration:
  realistic_seasons:
    use_time_system: true
    use_temperature_system: true
    enhanced_seasonal_effects: false  # Disabled for performance

# ======= PLAYER PREFERENCES =======
player_settings:
  allow_particle_toggle: true
  default_particles_enabled: true
  save_preferences: false

# ======= ENHANCED FEATURES (SELECTIVE) =======
enhanced_features:
  wind_trails:
    enabled: true
    stream_count_multiplier: 0.8  # Reduced
    trail_length: 4               # Reduced from 6

  blizzard_walls:
    enabled: true
    wall_density: 0.4    # Reduced from 0.6
    wall_height: 4       # Reduced from 6
    wall_width: 12       # Reduced from 15

  seasonal_wildlife:
    enabled: false  # Disabled for performance

  weather_transitions:
    enabled: true
    pre_storm_effects: true
    post_storm_effects: false     # Disabled for performance
    enhanced_lightning: true

# ======= DEBUG AND LOGGING (MINIMAL) =======
debug:
  enabled: false
  log_zone_changes: false
  log_temperature_changes: false
  log_drought_events: true
  log_performance: false
  log_particle_optimizations: false

# ======= NOTIFICATIONS (OPTIMIZED) =======
notifications:
  permission: "orbisclimate.notifications"
  zone_change_notifications: false    # Disabled to reduce spam
  drought_notifications: true
  temperature_warnings: true
  wind_event_notifications: false     # Disabled to reduce spam
  weather_progression_notifications: true

# ======= COMPATIBILITY =======
compatibility:
  # Disable features that conflict with other plugins
  disable_weather_override: false

  # Work with other particle plugins
  respect_particle_limits: true

  # Reduce effects near other plugin areas
  smart_area_detection: true

# ======= EXPERIMENTAL FEATURES (DISABLED) =======
experimental:
  particle_physics:
    enabled: false
  air_pressure:
    enabled: false
  dynamic_biome_temp:
    enabled: false
  ml_weather:
    enabled: false